version: '3'

services:
  prisma:
    container_name: learn-prisma
    build: .
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app:cached
      - node_modules:/usr/src/app/node_modules
      - dist:/usr/src/app/dist
    networks:
      my_network:
        ipv4_address: 172.30.0.2

  db:
    image: postgres:14
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=test
      - POSTGRES_PASSWORD=password
    networks:
      my_network:
        ipv4_address: 172.30.0.3

networks:
  my_network:
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.0/24

volumes:
  node_modules: {}
  dist: {}
  db:
